// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud_License_Managment_System.Models
{
    public partial class Products
    {
        public long Id { get; set; }
        public string ProductName { get; set; }
        public string UserId { get; set; }
        public string ProductDescription { get; set; }
        public string ProductVersion { get; set; }
        public bool? IsActive { get; set; }
    }
}